CREATE TABLE IF NOT EXISTS bsi_queue_message
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    BODY TEXT NOT NULL,
    HEADERS TEXT NOT NULL,
    QUEUE_NAME VARCHAR(190) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    AVAILABLE_AT DATETIME NOT NULL,
    DELIVERED_AT DATETIME DEFAULT NULL,
    PRIMARY KEY (ID),
    INDEX IX_BSQM_QUEUE_NAME(QUEUE_NAME),
    INDEX IX_BSQM_AVAILABLE_AT(AVAILABLE_AT),
    INDEX IX_BSQM_DELIVERED_AT(DELIVERED_AT)
);

CREATE TABLE IF NOT EXISTS bsi_queue_stat
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    UUID CHAR(36) NOT NULL,
    MESSAGE VARCHAR(190) NOT NULL,
    STATUS VARCHAR(190) NOT NULL,
    TRANSPORT VARCHAR(190) DEFAULT NULL,
    BUSES TEXT DEFAULT NULL,
    CREATED_AT DATETIME NOT NULL,
    RECEIVED_AT DATETIME DEFAULT NULL,
    HANDLED_AT DATETIME DEFAULT NULL,
    FAILED_AT DATETIME DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_BSQS_UUID(UUID),
    INDEX IX_BSQS_STATUS(STATUS),
    INDEX IX_BSQS_TRANSPORT(TRANSPORT),
    INDEX IX_BSQS_CREATED_AT(CREATED_AT),
    INDEX IX_BSQS_RECEIVED_AT(RECEIVED_AT),
    INDEX IX_BSQS_HANDLED_AT(HANDLED_AT),
    INDEX IX_BSQS_FAILED_AT(FAILED_AT)
);