CREATE TABLE IF NOT EXISTS bsi_queue_message
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    BODY TEXT NOT NULL,
    HEADERS TEXT NOT NULL,
    QUEUE_NAME VARCHAR(190) NOT NULL,
    CREATED_AT DATETIME NOT NULL ,
    AVAILABLE_AT DATETIME NOT NULL,
    DELIVERED_AT DATETIME DEFAULT NULL,
    PRIMARY KEY (ID),
    INDEX IX_BSQM_QUEUE_NAME(QUEUE_NAME),
    INDEX IX_BSQM_AVAILABLE_AT(AVAILABLE_AT),
    INDEX IX_BSQM_DELIVERED_AT(DELIVERED_AT)
);